#!/bin/bash
usage() { cat <<EOF
$*

Usage:
    backcp FILE         # cp --backup=t FILE FILE.bak
    backcp FILE DIR     # cp --backup=t FILE DIR/FILE
    backcp -t DIR FILE  # cp --backup=t FILE DIR/FILE
    backcp FILE1 FILE2  # cp --backup=t FILE1 FILE2
    backcp <(CMD) FILE2 # cp --backup=1 <(CMD) FILE2

Options:
    --help, -h, -?  show help
EOF
}
help_exit() {
	usage "copy FILE to FILE.bak or DIR/FILE."
	exit 0
}
error_exit() {
	usage $1 >&2
	exit 1
}
# parse command line
case $1 in
--help|-h|-\?|"") help_exit;;
-t)
	shift
	[ -z "$1" ] && error_exit "please specify DIR for -t"
	[ -d "$1" ] || mkdir "$1"
	[ -d "$1" ] || error_exit "please specify DIR for -t"
	dst=$1; src=$2;;
*)
	src=$1; dst=$2;;
esac
if [ -p "$src" ] && ([ -d "$dst" ] || [ -z "$dst" ]); then
	error_exit "$src is pipe, please specify FILE2"
fi
base=${src##*/} # BASE.EXT
[ -d "$dst" ] && dst=$dst/$base

# print exist backup-files and do backup
if [ -n "$dst" ] ; then
	[ -f "$dst" ] && ls -lFt $dst*
	[ -f "$src" ] && diff -sq $src $dst && exit 0
	cp -ip --backup=t $src $dst
else
	[ -f "$src" ] && ls -lFt $src*
	[ -f "$src.bak" ] && diff -sq $src{,.bak} && exit 0
	cp -ip --backup=t $src{,.bak}
fi
