#!/bin/bash
# diff to fuzzy backup file
function pushback {
	for f in $@; do
		if [ -f "$f" ] ; then back="$back $f"; fi
	done
}
function pushbackt {
	for f in $@; do
		pushback $f{,~,.~*~} # fname fname~ fname.~*~
	done
}
base=${1##*/} # BASE.EXT
noext=${1%.*} # DIR/BASE
dir=${1%/*}   # DIR

pushback $1{~,.~*~}		# fname~ fname.~*~
pushbackt $1.{bak,orig,save}	# fname.bak fname.orig fname.save
if [ ${noext:-$1} != $1 ] ; then
	pushbackt $noext.{bak,orig,save}
fi
if [ -n "$base" ] ; then
	pushbackt ~/{orig,save}/$base
	if [ "$PWD" != "$HOME" ] ; then
		pushbackt ./{orig,save}/$base
	fi
	if [ -d "$dir" ] ; then
		pushbackt $dir/{orig,save}/$base
	fi
fi
##echo "@:[$@], base:[$base], noext:[$noext], dir:[$dir], back:[$back]"
ls -ltFG $1
ls -ltFG $back | uniq
select sel in $(ls -1t $back | uniq); do
	diff $sel $@
	exit
done
