#!/bin/bash
cd ~
opt="-w ${@:--su}" # get diff-options
committmp=$(git config --get commit.template)
gitignore=$(git config --get core.excludesfile)
diff $opt bin/myvimrc    .vimrc
diff $opt bin/mytigrc    .tigrc
diff $opt bin/myminttyrc .minttyrc
diff $opt bin/mycommit_template $committmp
diff $opt bin/myignore          $gitignore
diff $opt bin/myeditorconfig    .editorconfig
