#!/bin/bash
if [ -d /etc/skel ]; then
	LANG=C diff -u -I "^#" /etc/skel ~ | grep -v ^Only.in
elif [ -d ~/orig ]; then
	for orig in ~/orig/.profile ~/orig/.bash* ; do
		LANG=C diff -u -I "^#" $orig ~ | grep -v ^Only.in
	done
fi
