#!/bin/bash
[ -e ~/.minttyrc ] && diff -swu ~/bin/myminttyrc ~/.minttyrc
[ -e ~/.vimrc    ] && diff -swu ~/bin/myvimrc    ~/.vimrc
[ -e ~/.tigrc    ] && diff -swu ~/bin/mytigrc    ~/.tigrc
committmp=$(git config --get commit.template)
[ -e $committmp  ] && diff -swu ~/bin/mycommit_template $committmp
gitignore=$(git config --get core.excludesfile)
[ -e $gitignore  ] && diff -swu ~/bin/myignore $gitignore
