#!/usr/bin/perl
if (!@ARGV || $ARGV[0] eq '-?') {
    print "usage: eachpath [-ENVNAME] command\n";
    exit 1;
}
$name = 'PATH';
if ($ARGV[0] =~ /^-(\w+)/) {
    $name = $1; shift;
}
print "* foreach \$$name do {@ARGV}\n";
foreach $d (split(q/:/,$ENV{$name})) {
    print "** $d\n";
    chdir($d);
    system(@ARGV);
}
