#!/bin/bash
# vim: set shiftwidth=4 tabstop=4 noexpandtab nosmarttab:
dst=$HOME/.bashrc
tmp=/tmp/bashrc
if grep "^## Note: bash login" $dst; then
	# すでに $dst へ書き出し済みならば、書き出し先を $tmp へ変更する.
	perl -pe "exit if /^## Note: bash login/;" $dst > $tmp
	dst=$tmp
fi
cat >>$dst <<- 'EOF'
	## Note: bash login workflow
	##  1. /etc/profile
	##  1a. /etc/bash.bashrc [Debian]
	##  2. ~/.bash_profile || ~/.bash_login || ~/.profile
	##  2a. ~/.bashrc
	##  2b. /etc/bashrc [Redhat]
	## Note: bash shell start workflow
	##  1. /etc/bash.bashrc [Debian]
	##  2. ~/.bashrc
	##  2a. /etc/bashrc [Redhat]
	## Note: bash logout
	##  1. ~/.bash_logout
	##
	[ -z "$PS1" ] && return # return if non-interactive-mode.
	[ -z "$LANG" ] && export LANG=ja_JP.UTF-8 # for macOS SSH
	## un-comment if you need.
	#HISTSIZE=2000
	#HISTFILESIZE=2000
	#alias poff='sudo poweroff'
	#alias boot='sudo reboot'
	#alias diff='diff --color=auto'
	#alias mount-clone='sudo mount /dev/sda2 /mnt/clone && lsblk'
	#alias umount-clone='sudo umount /mnt/clone && lsblk'
	#alias tailss='tailscale status'
	#alias tailup='tailscale up --ssh'
	#alias taildn='tailscale down'
	#alias start='xdg-open'
	#export EDITOR=vim
	#export GIT_EDITOR=vim
	#export GIT_PAGER=delta
	#export PAGER=lv
	#HISTTIMEFORMAT='%F %T '
	#HISTCONTROL=ignoreboth
	#HISTIGNORE='?:??:???:exit'
	#alias .a='source "$HOME/bin/myaliases"'
	#alias .b='source "$HOME/.bashrc"'
	#alias .f='source "$HOME/bin/myfunctions"'
	#source "$HOME/bin/myaliases"
	#source "$HOME/bin/myfunctions"
	#source /usr/share/doc/fzf/examples/key-bindings.bash
	#source /usr/share/doc/fzf/examples/completion.bash
	#GIT_PS1_SHOWUPSTREAM=1
	#GIT_PS1_SHOWDIRTYSTATE=1
	## MINGW64/GitBush: \[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$
	## Ubuntu18.04LTS: \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
	## Ubuntu22.04LTS: \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
	## RaspbianBuster: \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \$\[\033[00m\]
	## Cygwin64: \[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$
	## MacOS X Darwin: \h:\W \u\$
	#PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ ' ## colored for macOS
	#[ -z "$(type -t __git_ps1)" ] || PS1=${PS1/]\\w/]\\w\`__git_ps1\`}                               ## add __git_ps1 after PWD
	#[ -z "$(type -t __git_ps1)" ] || PS1=${PS1/]\\w/]\\w\\[\\033[36m\\]\`__git_ps1\`\\[\\033[0m\\]}  ## add colored __git_ps1 after PWD
	#[ -z "$(type -t lsb_release)" ] || PS1=${PS1/\}/\}\\[\\e[34m\\]`lsb_release -sd`*}               ## add distribution name for Ubuntu/Debian
	#PS1=${PS1/\\$/\\n\\$} ## add newline before $
	#PS1=${PS1/\\n/ \\A\\n} ## add 24time  before newline
	#PS1=${PS1/\\n/*\\j\\n} ## add jobs    before newline
	#PS1=${PS1/\\n/\`jobs\`\\n} ## add jobs before newline
	#PS1=${PS1/\\n/!\\!\\n} ## add history before newline
	#tabs -4
	#PROMPT_COMMAND=jobs
EOF
if [ "$dst" = "$tmp" ]; then
	DIFF=${DIFF:-diff ${@:--wu --color=auto}} # diffopt:: w:ignore-all-space, u:unified-style
	$DIFF $tmp $HOME/.bashrc
fi
