#!/bin/bash
cat >>$HOME/.bashrc <<- 'EOF'
	## un-comment if you need.
	#alias poff='sudo poweroff'
	#alias boot='sudo reboot'
	#alias diff='diff --color=auto'
	#alias mount-clone='sudo mount /dev/sda2 /mnt/clone && lsblk'
	#alias umount-clone='sudo umount /mnt/clone && lsblk'
	#alias start='xdg-open'
	#export EDITOR=vim
	#export GIT_EDITOR=vim
	#export PAGER=lv
	#HISTTIMEFORMAT='%F %T '
	#HISTCONTROL=ignoreboth
	#HISTIGNORE='?:??:???:exit'
	#source "$HOME/bin/myaliases" 2> /dev/null
	#source "$HOME/bin/myfunctions"
	#source "$HOME/bin/git-prompt.sh"
	#GIT_PS1_SHOWUPSTREAM=1
	#GIT_PS1_SHOWDIRTYSTATE=1
	## MINGW64/GitBush: \[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$
	## Ubuntu18.04LTS: \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
	## RaspbianBuster: \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \$\[\033[00m\]
	## Cygwin64: \[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$
	#PS1=${PS1/]\\w/]\\w\`__git_ps1\`}                               ## add __git_ps1 after PWD
	#PS1=${PS1/]\\w/]\\w\\[\\033[36m\\]\`__git_ps1\`\\[\\033[0m\\]}  ## add colored __git_ps1 after PWD
	#PS1=${PS1/\\$/\\n\\$}                                           ## add newline before $
	#PROMPT_COMMAND=jobs
EOF
