#!/usr/bin/perl
@PATH = split(":", $ENV{PATH});
foreach $d ("/sw/bin", "/sw-old/bin", "/opt/local/bin") {
#       push (@PATH, $d) unless grep(/$d/, @PATH);
}
foreach $a (@ARGV) {
        foreach $d (@PATH) {
                system("/bin/ls -lFG \"$d/$a\"") if -e "$d/$a";
        }
}

