#!/bin/sh
# vim: set filetype=sh tabstop=4 softtabstop=2 shiftwidth=2 expandtab cindent:
# init package
sudo add-apt-repository ppa:git-core/ppa
sudo apt update ; sudo apt -y upgrade
sudo apt -y install vim git tig nkf lv zip p7zip-full rar zstd xsel
# opt package
sudo apt install build-essential libtool automake autoconf pkg-config
sudo apt install cpanminus
sudo apt install npm && npm -g install electron
sudo apt install golang-go
sudo apt install libimage-exiftool-perl
sudo apt install libflickr-upload-perl
sudo apt-get autoremove
# init home
cd ~
[ -d orig ] || (mkdir orig save backup install ; sudo cp -p .* /etc/* orig/ ; dpkg --get-selections > save/pkg-selections)
[ -d bin  ] || git clone https://github.com/hkuno9000/cygbin.git bin
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh > bin/git-prompt.sh
bash -c bin/initmyrc
bash -c bin/initbashrc
bash -c bin/mygitconf
