#!/bin/bash
# vim: set filetype=sh et sta sts=2 sw=2 cindent:
yesno() {
  local yn
  case $1 in
    -c)
      shift
      read -r -p "$* [y/N] " yn
      case $yn in
        Y|y|yes)
          eval "$@"
          # do not use "true" here. keep command-status
          ;;
        *)
          false
          ;;
      esac
      return
      ;;
    -h|-\?|--help)
      echo 'usage: yesno "prompt"'
      echo '       yesno -c command arg1 arg2 ...'
      return
      ;;
  esac
  read -r -p "${*:-OK? [y/N]} " yn
  case $yn in
    Y|y|yes)
      true
      ;;
    *)
      false
      ;;
  esac
}

sudo() {
  if [ -x /usr/bin/sudo ]; then
    eval "command sudo $@"
  else
    # cygwin and git-for-windows have not native "sudo"
    eval "$@"
  fi
}

# init home dir
cd ~
mkdir save log backup install
if mkdir orig; then
  sudo cp -p .* orig/
  sudo cp -pr /etc orig/
  dpkg --get-selections > orig/pkg-selections.log
  alias    > orig/alias.log
  printenv > orig/printenv.log
  apt list > orig/apt-list.log
  groups   > orig/groups.log
fi
# mysetting
yesno -c LANG=C xdg-user-dirs-gtk-update
yesno -c sudo LANG=C dpkg-reconfigure keyboard-configuration
diff {~/orig/,/}etc/default/keyboard
# install minimum package
if [ -x /usr/bin/apt-get ]; then
yesno -c sudo add-apt-repository ppa:git-core/ppa
sudo apt update ; sudo apt full-upgrade
sudo apt install vim git tig zip curl wget
# install option package
cp -p install/mypkg install/mypkg.save
cat > install/mypkg << EOF
## vim: set filetype=sh et sta sts=2 sw=2 cindent:
$(grep -h -E "^sudo (apt|apt-get) install" install/mypkg.save ~/.bash_history | sort -u)
## un-comment if you need.
#sudo apt install language-pack-ja && sudo update-locale LANG=ja_JP.UTF-8
#sudo apt install ripgrep
#sudo apt install dos2unix nkf
#sudo apt install eza
#sudo apt install fzf
#sudo apt install p7zip-full
#sudo apt install zstd
#sudo apt install rar
#sudo apt install xsel # need X11
#sudo apt install fdclone vifm
#sudo apt install gh
#sudo apt install meld
#sudo apt install gitk
#sudo apt install git-delta
#sudo apt install git-svn
#sudo apt install git-cvs
#sudo apt install subversion
#sudo apt install make
#sudo apt install build-essential
#sudo apt install libtool automake autoconf pkg-config
#sudo apt install cpanminus
#sudo apt install npm && npm -g install electron
#sudo apt install golang
#sudo apt install rustc
#sudo apt install lua5.3
#sudo apt install ziglang
#sudo apt install libimage-exiftool-perl
#sudo apt install libflickr-upload-perl
#sudo apt install astronomical-almanac
#sudo apt install terminator
#sudo apt install plantuml
#sudo apt install google-chrome-stable
#sudo apt install network-manager
#sudo apt install whois
#sudo apt install neovim
#sudo apt install ffmpeg
#sudo apt install imagemagick
#sudo apt install graphicsmagick
#sudo apt install graphicsmagick-imagemagick-compat
#sudo apt install libsixel-bin
#sudo apt install w3m
#sudo apt-get autoremove
EOF
cat >> install/mypkg << 'EOF'
## === ubuntu-ja
## https://www.ubuntulinux.jp/News/ubuntu2404-ja-remix
##  Japanese Teamのパッケージレポジトリを追加する.
## リポジトリ追加後、パッケージ情報の更新時に以下の警告が表示されますが、これはUbuntu 24.04 LTSから1024ビットRSAによるAPTリポジトリ署名鍵が非推奨になったことによるものです。
## Launchpad PPAでの再署名と鍵の更新が完了後、この警告は表示されなくなる予定です。
## W: http://archive.ubuntulinux.jp/ubuntu/dists/noble/InRelease: Signature by key 59676CBCF5DFD8C1CEFE375B68B5F60DCDC1D865 uses weak algorithm (rsa1024)
#sudo wget https://www.ubuntulinux.jp/sources.list.d/noble.sources -O /etc/apt/sources.list.d/ubuntu-ja.sources
#sudo apt -U upgrade
#sudo apt install ubuntu-defaults-ja
## === code
#GPGKEY=/usr/share/keyrings/microsoft-packages-keyring.gpg
#curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o $GPGKEY
#echo "deb [arch=amd64 signed-by=$GPGKEY] https://packages.microsoft.com/repos/vscode stable main" | sudo tee /etc/apt/sources.list.d/vscode.list
#sudo apt update ; sudo apt install code
## === google-chrome-stable
#GPGKEY=/usr/share/keyrings/google-dl-keyring.gpg
#curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o $GPGKEY
#echo "deb [arch=amd64 signed-by=$GPGKEY] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
#sudo apt update ; sudo apt install google-chrome-stable
## === anydesk
## http://deb.anydesk.com/howto.html
#GPGKEY=/usr/share/keyrings/anydesk-keyring.gpg
#curl -fsSL https://keys.anydesk.com/repos/DEB-GPG-KEY | sudo gpg --dearmor -o $GPGKEY
#echo "deb [arch=amd64 signed-by=$GPGKEY] http://deb.anydesk.com/ all main" | sudo tee /etc/apt/sources.list.d/anydesk-stable.list
#sudo apt update ; sudo apt install anydesk
EOF
vim install/mypkg ; source install/mypkg
fi

# WSL patch
if yesno "WSL [y/N]"; then
  cat <<-'EOF' | sudo tee -a /etc/wsl.conf
# global setting is: ${USERPROFILES}/.wslconfig
# ------
# avoid to lost focus on WindowsApp by WSL <https://jiyuukaitakusha.com/howto-deal-focus-loss/>
#[wsl2]
#guiApplications=false
# ------
# avoid => WSL (1015) ERROR: UtilTranslatePathList:2866: Failed to translate X:\path\to\windows-network-drive
[interop]
appendWindowsPath=false
EOF
EDITOR=vim sudoedit /etc/wsl.conf
fi

# init shell and git
yesno -c git clone https://github.com/hkuno9000/cygbin.git bin
if yesno "git user.name/email hkuno [y/N]"; then
  git config --global user.name "Hiroshi Kuno"
  git config --global user.email "hkuno9000@gmail.com"
fi
##curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh > bin/git-prompt.sh
yesno -c bash -c bin/initmyrc
yesno -c bash -c bin/initbashrc
vim -c '/^##' .bashrc
yesno -c bash -c bin/mygitconf
# end
