#!/bin/sh
# my config
LANG=C xdg-user-dirs-gtk-update
sudo locale-gen ja_JP.EUC-JP
sudo localedef -f SHIFT_JIS -i ja_JP ja_JP.SJIS
gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
[ -d /C: ] || (sudo mkdir /C: ; sudo ln -s /home /C:/Users)
timedatectl status
