#!/bin/sh
# vim: set filetype=sh softtabstop=2 shiftwidth=2 smarttab cindent:
echo === dist
lsb_release -a
echo === uname
uname -a
echo == lscpu
lscpu
echo more: cat /proc/cpuinfo
echo == lsusb
lsusb
echo == lsblk
lsblk
echo === ip
ip route
echo === wifi
nmcli device wifi
