#!/bin/sh
# vim: set filetype=sh tabstop=4 softtabstop=2 shiftwidth=2 expandtab cindent:
echo === dist
lsb_release -a
echo === uname
uname -a
echo == lscpu
lscpu
echo == cpuinfo
cat /proc/cpuinfo
echo === ip
ip route
