#!/bin/sh
# vim: set filetype=sh softtabstop=2 shiftwidth=2 smarttab cindent:
echo === dist
lsb_release -a
echo === os-release
cat /etc/os-release
echo === uname
uname -a
echo === model
more /proc/device-tree/model
echo == lscpu
lscpu
echo more: cat /proc/cpuinfo
echo == lsusb
lsusb && lsusb -t
echo == lsblk
lsblk
echo === ip
ip route
echo === wifi
nmcli device wifi
