#!/bin/sh
# vim: set filetype=sh tabstop=4 softtabstop=2 shiftwidth=2 expandtab cindent:
sudo apt update
sudo apt -y upgrade
sudo systemctl daemon-reload
sudo apt-get autoremove
[ -d ~/.cpan ] && sudo cpan upgrade
