#!/bin/sh
perl -lne 'BEGIN{print qq/=== $ARGV[0]/;} $hosts{$1} .= " $2" if /^(\w\S+) (\S+)/; END{ while (my($host,$types) = each %hosts) {print "$host:$types";} }' $HOME/.ssh/known_hosts
perl -lne 'BEGIN{print qq/\n=== $ARGV[0]/;} print $& if /^Host \S+/;'  $HOME/.ssh/config
